### ISSUE TITLE
Import CIFAR-10

### ISSUE THREAD

**Issue by alialani12** [dnlcrl/PyDatSet#2]
Hi guys,

I am already imported the MNIST dataset and train on to the DBN, from the following code 

from sklearn import datasets
print "[X] downloading data..."
dataset = datasets.fetch_mldata("MNIST Original")

(trainX, testX, trainY, testY) = train_test_split(
	dataset.data / 255.0, dataset.target.astype("int0"), test_size = 0.16)

and the data was in this shape

trainX = [58000L,784L)
testX = [12000L, 10L)
trainX = [58000L,)
testX = [12000L, )

Please, I need help to import the cifar10 in the same way I imported the MNIST and return the same format. I have tried researching on the internet but there is hardly any help available. Any expert help related to solving this error will be much appreciated.

regards

**Comment by dnlcrl** [comment]
Hi, 

You are using sklearn, not pydatset, you should ask your questions about sklearn here: https://github.com/scikit-learn/scikit-learn

Anyway if you google "load cifar10 sklearn" you will find a ton of tutorials and guides on how to load your datasets with sklearn.
